{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.0.3.jar",
          "url": "gradle-api-7.0.3.jar",
          "size": 222798,
          "sha512": "d4f336ae4195e42b1b2aa19676eee286ccb379ed5ac20497746cc50a768c20651bcb62cd6c425fe3d71adc4a86a116a6153079e0b43e199f4d8f78e5cb480899",
          "sha256": "ebe10a58f43035bbcf18c2ab3d8c15a9b27bbd1af5ba83a147ae87ff07045c73",
          "sha1": "ac920489d2c4be1cd93bbd75648a7f3a491df4f0",
          "md5": "5d11ed85a8e3ece9171a0ad7184d651e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.0.3.jar",
          "url": "gradle-api-7.0.3.jar",
          "size": 222798,
          "sha512": "d4f336ae4195e42b1b2aa19676eee286ccb379ed5ac20497746cc50a768c20651bcb62cd6c425fe3d71adc4a86a116a6153079e0b43e199f4d8f78e5cb480899",
          "sha256": "ebe10a58f43035bbcf18c2ab3d8c15a9b27bbd1af5ba83a147ae87ff07045c73",
          "sha1": "ac920489d2c4be1cd93bbd75648a7f3a491df4f0",
          "md5": "5d11ed85a8e3ece9171a0ad7184d651e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.0.3-javadoc.jar",
          "url": "gradle-api-7.0.3-javadoc.jar",
          "size": 465183,
          "sha512": "e2f437907f750c9e5b9cf4a930466d59d4b820341be8669df80325eb9f2cb675ecdf5e41ecd7a5efe00c6135e25012cfc29b69c3bcf6ea59799bffd68e15e31f",
          "sha256": "a8ad87b687d37cb25784c7fa9d842a953c84a704642170a793fee3a59681c990",
          "sha1": "d0c2f74415aee01b1659c6ef11baaf98214dffc0",
          "md5": "46eca183c7bc2919df600430dbbe99fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.0.3-sources.jar",
          "url": "gradle-api-7.0.3-sources.jar",
          "size": 219919,
          "sha512": "51c1aacba68d2fb6112c0b168967ab43ae2659ba026dd2523bcf8a07ca9087b505e86363046a9b29cfdfbf03a65b533e2c85f483bd406a08a13df64e9b56f6a4",
          "sha256": "23f0827c729090b68889d91634640bf2ac09e0e11903d643a892ae72ff7c72cc",
          "sha1": "aefa653cd6aba6b4a2bb9febca9810cabb4c7d3b",
          "md5": "004bac8a71ded6a676ea661f69105d44"
        }
      ]
    }
  ]
}
