{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.constraintlayout",
    "module": "constraintlayout",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "constraintlayout-2.1.1.aar",
          "url": "constraintlayout-2.1.1.aar",
          "size": 473236,
          "sha512": "da0b6cd794d0a80d9cd8405e48b612e6813d68fc2ab76d68960d86edde0d717282a0574910eed12745410cfa3cda7ab62862f46261645144598863ed9d211489",
          "sha256": "20879399bd732f67a3445a1ca060b78cb43164aca705b779e385ea2ebd0d3d79",
          "sha1": "23c15d5806b2ffc01e6a4c23d0b453e401a66c6d",
          "md5": "f08e69d0561f481398703a7015d11f73"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-core",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-2.1.1.aar",
          "url": "constraintlayout-2.1.1.aar",
          "size": 473236,
          "sha512": "da0b6cd794d0a80d9cd8405e48b612e6813d68fc2ab76d68960d86edde0d717282a0574910eed12745410cfa3cda7ab62862f46261645144598863ed9d211489",
          "sha256": "20879399bd732f67a3445a1ca060b78cb43164aca705b779e385ea2ebd0d3d79",
          "sha1": "23c15d5806b2ffc01e6a4c23d0b453e401a66c6d",
          "md5": "f08e69d0561f481398703a7015d11f73"
        }
      ]
    }
  ]
}
