{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "apkzlib",
    "version": "7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "apkzlib-7.0.3.jar",
          "url": "apkzlib-7.0.3.jar",
          "size": 202778,
          "sha512": "a4c7d2f7c334cc1e8c217e17be52fd86621283094ab51f604c69f7a1baf07578a9e654429ad83e756a98c555736fa1c6549a23e30759844ff2bb2d0349b4ac74",
          "sha256": "b31e53174c92db83c5cc6e7dac6734ea4e907a72e452c2bf1818dfd082c59397",
          "sha1": "caefc8368f8bb86e2d5d5fc4467f2fe0ad9ad4d4",
          "md5": "9f76f5273e52c2ed03af346908a5f0ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "7.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "apkzlib-7.0.3.jar",
          "url": "apkzlib-7.0.3.jar",
          "size": 202778,
          "sha512": "a4c7d2f7c334cc1e8c217e17be52fd86621283094ab51f604c69f7a1baf07578a9e654429ad83e756a98c555736fa1c6549a23e30759844ff2bb2d0349b4ac74",
          "sha256": "b31e53174c92db83c5cc6e7dac6734ea4e907a72e452c2bf1818dfd082c59397",
          "sha1": "caefc8368f8bb86e2d5d5fc4467f2fe0ad9ad4d4",
          "md5": "9f76f5273e52c2ed03af346908a5f0ce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-7.0.3-javadoc.jar",
          "url": "apkzlib-7.0.3-javadoc.jar",
          "size": 699283,
          "sha512": "96377e92b42953ac99b51f85a9358c0ae10b608e7620cc5e81ce4f28c6302071123c110620efb297d4ba055ce356237d7bb551c5ded0df3e9c9d3a9375e6e8f9",
          "sha256": "589ace25c0454e6cd45b438101226d1cfca076b278ed61b529afdd98cc37815c",
          "sha1": "ea40b150128dcc1a219f8a275dc659b0cde62219",
          "md5": "3e0276c30845e527538eccc47f388276"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-7.0.3-sources.jar",
          "url": "apkzlib-7.0.3-sources.jar",
          "size": 175631,
          "sha512": "8bd644e23e50676ae1024dac5737cc599ae6f0d96ea51985cabd20706f61a4061c543dd4c6e2429990f3d9d64cfb91aa002b77a62a6fee6190da618c392ba13f",
          "sha256": "b3acefd6417da66ddf280dbcabe9ca6eecfec2fec7eda06e34e8f5c37f1955dc",
          "sha1": "5bb34c57b82b4454fced5364b6feb1e72b769853",
          "md5": "48fa705fec0524ef6ef3f2be271e8b7b"
        }
      ]
    }
  ]
}
